-- Create a table to store chat history
create table if not exists chat_history (
  id bigint generated by default as identity primary key,
  user_id text not null,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamp with time zone default now()
);

-- Create an index to speed up fetching history by user_id
create index if not exists idx_chat_history_user_id on chat_history(user_id);

-- Enable RLS (Row Level Security)
alter table chat_history enable row level security;

-- Allow the Service Role (used by Edge Function) to have full access
create policy "Service Role Full Access"
on chat_history
for all
to service_role
using (true)
with check (true);
