-- Create stores table for location-based search
create table if not exists stores (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  lat double precision not null,
  lng double precision not null,
  phone text,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- Enable RLS
alter table stores enable row level security;

-- Public Read Access
create policy "Public Read Access"
on stores for select
using (true);

-- Service Role Full Access
create policy "Service Role Full Access"
on stores for all
to service_role
using (true)
with check (true);

-- Seed initial store data
-- 車水馬容: 臺北市大同區民族西路305號
-- Approximate coordinates: 25.0657, 121.5130
insert into stores (name, address, lat, lng, phone) values
('車水馬容', '臺北市大同區民族西路305號', 25.0657, 121.5130, NULL);
