-- Create a table for Service Menu
create table if not exists services (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null, -- 'TIERED' (Small/Med/Large) or 'FLAT' (Single Price)
  description text,
  price_small text, -- Store as text to allow ranges like "1200-1500" if needed, or simple numbers
  price_medium text,
  price_large text,
  price_flat text,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- Enable RLS
alter table services enable row level security;

-- Policies
-- 1. Public Read (Anyone can see services)
create policy "Public Read Access"
on services for select
using (true);

-- 2. Service Role Full Access (For Admin & Bot)
create policy "Service Role Full Access"
on services for all
to service_role
using (true)
with check (true);

-- 3. Authenticated Admin Access (Assuming authenticated users are admins for now)
create policy "Admin Full Access"
on services for all
to authenticated
using (true)
with check (true);

-- Seed Initial Data
insert into services (name, category, price_small, price_medium, price_large, description) values
('精緻洗車', 'TIERED', '800', '1,000', '1,200−1,500', '含泡沫洗車、內裝基礎清潔'),
('汽車小美容', 'TIERED', '3,500', '4,500', '5,500−6,500', '車漆增艷、深層去污'),
('汽車大美容', 'TIERED', '7,500', '9,000', '11,000−13,000', '漆面校正、鏡面拋光'),
('汽車鍍膜', 'TIERED', '12,000', '16,000', '20,000−30,000', '全車陶瓷鍍膜，保固一年');

insert into services (name, category, price_flat, description) values
('玻璃油膜去除 + 撥水鍍膜', 'FLAT', '1,200', '全車玻璃處理'),
('引擎室細節護理', 'FLAT', '2,000', '引擎室油污深層清潔與上油'),
('皮革深層清潔保養', 'FLAT', '2,500', '皮椅深層去污滋潤'),
('大燈泛黃修復', 'FLAT', '1,500', '雙側大燈拋光重建 (還原透亮度)');
